# -*- coding: utf-8 -*-
"""2311cs020531 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LDzSpuxj83Dc0jScyGK-m-zmvmo7_v66
"""

list = [1,2,3,4,5,6,7,8,9]
res = {i for i in list if i % 2 == 0}
print("Even numbers", res)